# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-github-oidc-provider
  description: This component is responsible for authorizing the GitHub OIDC provider as an Identity provider for an AWS account
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component
